### PR TITLE
MGMT-15330: Make the custom manifest YAML editor read-only

### PR DESCRIPTION
**Pull request by jgyselov**
https://issues.redhat.com/browse/MGMT-15330

### CODE REVIEW

**Comment by ammont82** [comment]
@jgyselov these changes don't affect tests for yaml's upload?

**Comment by jgyselov** [comment]
> @jgyselov these changes don't affect tests for yaml's upload?

If it did, the test wouldn't pass without changes. (We are using the upload function in the tests, we are not typing the YAMLs manually.)

**Comment by ammont82** [comment]
> > @jgyselov these changes don't affect tests for yaml's upload?
> 
> If it did, the test wouldn't pass without changes. (We are using the upload function in the tests, we are not typing the YAMLs manually.)

Perfect. Sorry, I wrote my comment before all tests passed. Good job

**Comment by jgyselov** [comment]
> Perfect. Sorry, I wrote my comment before all tests passed.

I usually run the tests locally before I push to GH. So in case they fail, I can properly look into it right away. :slightly_smiling_face:

**Review by jkilzi — APPROVED** [review]

**Comment by jkilzi** [comment]
@talhil-rh FYI

**Pull request merged**
